plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.destinytg.device'
    compileSdk 35

    defaultConfig {
        applicationId 'com.destinytg.device'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }

        python {
            version '3.11'
            pip {
                install 'kurigram==2.2.25'
            }
        }
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            universalApk true
        }
    }

    sourceSets.main.python.srcDirs = ['src/main/python']

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}